################################################################################
# Example of docker-compose to setup Cognos with DB2-Developer-C and Cloudera
#
# WARNING: The resulting container image is not suitable for any production 
#          use and should be used for demonstration purposes only
#
# Written by    Philippe Gregoire (philippe.gregoire@fr.ibm.com)
#               IBM Ecosystem Advocacy Group Europe 
#
# Copyright 2019, IBM Corporation
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
version: "3"
services:
  db2-c:
    build: ./phg-centos7-xfce-cognos/db2-dev-c
    image: store/ibmcorp/db2_developer_c:11.1.4.4-x86_64_CM
    container_name: db2server
    hostname: db2server_
    privileged: true
    ports:
      - "50000:50000"
      - "55000:55000"
    volumes:
      - db2cogdata:/database 
      - shared:/shared
    env_file:
      ./phg-centos7-xfce-cognos/db2-dev-c/db2_env
    restart: always
    
  cognosca11_1:
    build: ./phg-centos7-xfce-cognos/cognosca
#    depends_on:
 #     - db2-c
 #     - cloudera_qs
    image: phg/centos7-cognosca:11.1
    container_name: cognos11cnr
    hostname: cognos11srv
    ports:
      - "5901:5901"
      - "6901:6901"
      - "9300:9300"
    environment:
      # Define the following environemnt variables to control Cognos startup
      - COGNOS_WAIT_DB2_MINS
      - COGNOS_MAX_RETRIES
    volumes:
      - shared:/shared      

  cloudera_qs:
    image: cloudera/quickstart:import
    container_name: cloudera_qs
    hostname: quickstart.cloudera
    entrypoint: /bin/bash -c "/usr/bin/docker-quickstart && exec bash"
#    command: /bin/bash -c
#    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
      - "80:80"
      - "7180:7180"
      # Sqoop and sqoop admin ports
      - "12000:12000"
      - "12001:12001"
      # Oozie, oozie admin and SSL ports:
      - "11000:11000"
      - "11001:11001"
      - "11443:11443"
      # Impala
      - "21000:21000"
      - "21050:21050"
      - "25000:25000"
      - "25010:25010"
      - "25020:25020"
    volumes:
      - shared:/shared
    
volumes:
  db2cogdata:
    external: true
  shared:
    external: true